### PR TITLE
Subsidiary accounts can log in - Fix

### LINKED ISSUE #136: Subsidiary accounts can log in
Just accidentally logged into the site as @sherson with the "rtic" account.  It's not a major issue, but it does mean that the TRSpvs can log in as Don pretty easily since they both have access to an account that's "Don's"

In round-three we guard against this by checking whether 
```ruby
request.env["UMAPrimaryAccount"] == request.env["uid"]
```

See umts/round-three#29

### PR DESCRIPTION
**Pull request by AkivaGreen**
I want to resolve #136 with this pull request.

### CODE REVIEW

**Comment by dfaulken** [comment]
Seems simple enough for handling the request that Shibboleth makes after people are redirected there initially. How about once people are using the site? Does this work because `nil == nil`?

**Comment by AkivaGreen** [comment]
In development it works because `nil == nil`. However, in production it seems to actually work.
- vaguely quoting Matt

**Comment by dfaulken** [comment]
Okay - though since some tests are what's needed to finish this PR up anyway, might be nice to write one to verify that this works when neither of those request parameters are present.

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -9,6 +9,7 @@ class ApplicationController < ActionController::Base
   before_action :set_current_user
   before_action :redirect_unauthenticated
   before_action :access_control
+  before_action :primary_account
```
Comment (dfaulken) [inline app/controllers/application_controller.rb]: To be fair, `:access_control` just above wasn't a great example, but it's nice to phrase methods like these as an imperative, e.g. `check_primary_account`, `handle_subsidiary_accounts`, etc.

File: app/views/sessions/unauthenticated_subsidiary.haml [hunk 2]
```diff
@@ -0,0 +1,5 @@
+%h1 Login failure
+Role subsidiary accounts can not be used to access this site. Please login with your primary NetID.
```
Comment (dfaulken) [inline app/views/sessions/unauthenticated_subsidiary.haml]: `cannot` is more common usage than `can not`

**Comment by dfaulken** [comment]
What do we think, @sherson? Is the text written in that warning HAML page going to be understood by people who encounter this problem? (I have absolutely no clue who these people are, besides Matt / his LastPass extension of course).

**Comment by sherson** [comment]
Looks OK to me... if they don't know what a role subsidiary account is, they'll email us.

That written, I suppose we could be extra verbose:

> You are attempting to login with `uid `, which is a role subsidiary account belonging to `UMAPrimaryAccount`. Role subsidiary accounts can not be used to access this site. Please login with your primary NetID. If you need assistance, contact transit-it@admin.umass.edu.

**Comment by sherson** [comment]
> I have absolutely no clue who these people are, besides Matt / his LastPass extension of course

Some examples of my subsidiary accounts: A few staff at PVTA (in case we need to grant them VPN access to reach the camera system), TPA (for their email), and several -af accounts (for student staff AD logins).

**Comment by dfaulken** [comment]
Sounds good, thanks for clarifying. Couple of small changes as I suggested and this is good to go.

**Comment by dfaulken** [comment]
Great, some request specs will finish this up.

**Comment by dfaulken** [comment]
Also rubocop.

File: spec/controllers/dashboard_controller_spec.rb [hunk 3]
```diff
@@ -119,4 +119,30 @@
       end
     end
   end
+
+  describe 'Check Primary Account' do
+    let(:admin) { create :user, :admin }
```
Comment (dfaulken) [inline spec/controllers/dashboard_controller_spec.rb]: Since we only need one user per context, better to create them at that level.

Comment (dfaulken) [inline spec/controllers/dashboard_controller_spec.rb]: And since there's only one test per context, you can just write

```ruby
when_current_user_is :student
```

and

```ruby
when_current_user_is :admin
```

File: spec/controllers/dashboard_controller_spec.rb [hunk 4]
```diff
@@ -119,4 +119,30 @@
...
+    let(:student) { create :user, :student }
+    context 'login as subsidiary account' do
+      it 'renders unauthenticated subsidiary haml' do
+        when_current_user_is student
+        request.env['uid'] = student.id
+        request.env['UMAPrimaryAccount'] = admin.id
+        get :main
+        expect(response)
+          .to render_template 'sessions/unauthenticated_subsidiary'
+        expect(response).not_to redirect_to '/dashboard/student'
```
Comment (dfaulken) [inline spec/controllers/dashboard_controller_spec.rb]: Generally nicer to use the path helper, e.g. `student_dashboard_path`.

File: spec/controllers/dashboard_controller_spec.rb [hunk 5]
```diff
@@ -119,4 +119,30 @@
...
     end
   end
+
+  describe 'Check Primary Account' do
+    let(:admin) { create :user, :admin }
+    let(:student) { create :user, :student }
+    context 'login as subsidiary account' do
+      it 'renders unauthenticated subsidiary haml' do
+        when_current_user_is student
+        request.env['uid'] = student.id
```
Comment (dfaulken) [inline spec/controllers/dashboard_controller_spec.rb]: `request.env.merge!` would be a little shorter here, if that's defined.

File: spec/controllers/dashboard_controller_spec.rb [hunk 6]
```diff
@@ -119,4 +119,29 @@
       end
     end
   end
+
+  describe 'Check Primary Account' do
+    context 'login as subsidiary account' do
+      it 'renders unauthenticated subsidiary haml' do
+        when_current_user_is :student
+        admin = create :user, :admin
+        request.env.merge!({ 'uid' => session[:user_id],
```
Comment (dfaulken) [inline spec/controllers/dashboard_controller_spec.rb]: Don't need parentheses or curly braces here.

Comment (AkivaGreen) [inline spec/controllers/dashboard_controller_spec.rb]: Sadly, without the parenthesis the it won't work.

Comment (werebus) [inline spec/controllers/dashboard_controller_spec.rb]: It will, but you have to drop the curly braces too.  This is because curly braces are also the way ruby syntax specifies a block argument to a method, but what you have isn't a valid block.

```ruby
request.env.merge! 'uid' => 'session[:user_id],
                   'UMAPrimaryAccount' => admin.id
```

Should be valid, I think.

Comment (AkivaGreen) [inline spec/controllers/dashboard_controller_spec.rb]: It works, thanks!
